export const SOURCES: Record<
  string,
  { name: string; color: string; lightColor: string; cssClass: string }
> = {
  roadtovr: {
    name: "Road to VR",
    color: "#00e5ff",
    lightColor: "#0891B2",
    cssClass: "source-roadtovr",
  },
  uploadvr: {
    name: "UploadVR",
    color: "#e040fb",
    lightColor: "#C026D3",
    cssClass: "source-uploadvr",
  },
  techcrunch: {
    name: "TechCrunch",
    color: "#00e676",
    lightColor: "#059669",
    cssClass: "source-techcrunch",
  },
  xrtoday: {
    name: "XR Today",
    color: "#ff9100",
    lightColor: "#EA580C",
    cssClass: "source-xrtoday",
  },
  mixed: {
    name: "Mixed News",
    color: "#ffe082",
    lightColor: "#D97706",
    cssClass: "source-mixed",
  },
  ghosthowls: {
    name: "Ghost Howls",
    color: "#2dd4bf",
    lightColor: "#0D9488",
    cssClass: "source-ghosthowls",
  },
  hypergrid: {
    name: "Hypergrid Business",
    color: "#818cf8",
    lightColor: "#4F46E5",
    cssClass: "source-hypergrid",
  },
  xrnews: {
    name: "XR News",
    color: "#fb7185",
    lightColor: "#E11D48",
    cssClass: "source-xrnews",
  },
  theverge: {
    name: "The Verge",
    color: "#448aff",
    lightColor: "#2563EB",
    cssClass: "source-theverge",
  },
  arstechnica: {
    name: "Ars Technica",
    color: "#ff5252",
    lightColor: "#DC2626",
    cssClass: "source-arstechnica",
  },
  venturebeat: {
    name: "VentureBeat",
    color: "#ce93d8",
    lightColor: "#7C3AED",
    cssClass: "source-venturebeat",
  },
  vrorg: {
    name: "VR.org",
    color: "#00e5ff",
    lightColor: "#0891B2",
    cssClass: "source-vrorg",
  },
};

export const CATEGORIES = [
  { key: "all", label: "All" },
  { key: "hardware", label: "Hardware" },
  { key: "gaming", label: "Gaming" },
  { key: "software", label: "Software" },
  { key: "enterprise", label: "Enterprise" },
  { key: "ar", label: "AR / Spatial" },
] as const;

export const COMPANY_FILTERS = [
  { key: "meta", label: "Meta" },
  { key: "apple", label: "Apple" },
  { key: "valve", label: "Valve / Steam" },
  { key: "sony", label: "Sony / PSVR" },
] as const;

export const MOCK_ARTICLES = [
  {
    id: "1",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "Valve Confirms Steam Frame Standalone VR Headset Still Shipping in 2026",
    snippet:
      "Valve's upcoming standalone VR headset is still on track for release this year, the company says, as anticipation builds for what could be a major new entrant in the standalone space.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 2 * 3600000).toISOString(),
    category: "hardware",
    tags: ["valve", "hardware"],
    imageUrl: null,
  },
  {
    id: "2",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "Hackers Claim to Have Effectively 'Jailbroken' PSVR 2 for PC",
    snippet:
      "A hardware hacker group previously behind the PSVR2Toolkit says it has effectively enabled full PC VR functionality on Sony's headset, bypassing official adapter limitations.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 4 * 3600000).toISOString(),
    category: "hardware",
    tags: ["sony", "hardware"],
    imageUrl: null,
  },
  {
    id: "3",
    source: "uploadvr",
    sourceName: "UploadVR",
    title: "Meta Quest Usage Hits All-Time High in 2025, Boosting Developer Revenue",
    snippet:
      "Meta's Director of Games revealed that Quest platform usage reached record levels last year, helping developers earn significantly more through the Quest Store ecosystem.",
    link: "https://uploadvr.com",
    author: null,
    pubDate: new Date(Date.now() - 5 * 3600000).toISOString(),
    category: "enterprise",
    tags: ["meta", "enterprise"],
    imageUrl: null,
  },
  {
    id: "4",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "Little Nightmares VR: Altered Echoes Announced for April Release",
    snippet:
      "Bandai Namco revealed that its acclaimed puzzle-platformer franchise is making the leap to VR with an all-new storyline and immersive gameplay mechanics.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 6 * 3600000).toISOString(),
    category: "gaming",
    tags: ["gaming"],
    imageUrl: null,
  },
  {
    id: "5",
    source: "techcrunch",
    sourceName: "TechCrunch",
    title: "Apple Vision Pro 2 Reportedly Entering Mass Production With Lighter Design",
    snippet:
      "Apple's next-generation spatial computer is said to feature a significantly lighter build, improved passthrough, and a more competitive price point aimed at broader adoption.",
    link: "https://techcrunch.com",
    author: null,
    pubDate: new Date(Date.now() - 7 * 3600000).toISOString(),
    category: "hardware",
    tags: ["apple", "hardware", "ar"],
    imageUrl: null,
  },
  {
    id: "6",
    source: "xrtoday",
    sourceName: "XR Today",
    title: "Enterprise XR Spending to Reach $40B by 2028, New Report Finds",
    snippet:
      "A new market analysis projects massive growth in enterprise adoption of XR technologies, driven by training, remote assistance, and digital twin applications.",
    link: "https://www.xrtoday.com",
    author: null,
    pubDate: new Date(Date.now() - 8 * 3600000).toISOString(),
    category: "enterprise",
    tags: ["enterprise", "ar"],
    imageUrl: null,
  },
  {
    id: "7",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "John Carmack Questions Meta's Developer Incentive Structure for Horizon",
    snippet:
      "The legendary programmer and former Oculus CTO shared concerns about the health of Meta's approach to incentivizing game development on the Horizon platform.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 9 * 3600000).toISOString(),
    category: "software",
    tags: ["meta", "software"],
    imageUrl: null,
  },
  {
    id: "8",
    source: "theverge",
    sourceName: "The Verge",
    title: "Steam VR Concurrent Users Break Monthly Record as Frame Hype Builds",
    snippet:
      "Steam's VR usage metrics are surging ahead of the anticipated Steam Frame launch, with concurrent VR users hitting new highs across the platform.",
    link: "https://www.theverge.com",
    author: null,
    pubDate: new Date(Date.now() - 10 * 3600000).toISOString(),
    category: "gaming",
    tags: ["valve", "gaming"],
    imageUrl: null,
  },
  {
    id: "9",
    source: "uploadvr",
    sourceName: "UploadVR",
    title: "The Boys: Trigger Warning — Amazon's Hit Series Coming to VR",
    snippet:
      "Amazon announced an immersive VR adventure based on The Boys franchise, promising action-packed gameplay in the show's signature irreverent style.",
    link: "https://uploadvr.com",
    author: null,
    pubDate: new Date(Date.now() - 11 * 3600000).toISOString(),
    category: "gaming",
    tags: ["gaming"],
    imageUrl: null,
  },
  {
    id: "10",
    source: "mixed",
    sourceName: "Mixed News",
    title: "Nvidia GeForce NOW Adds VR Framerate Boost for Cloud Gaming",
    snippet:
      "Nvidia announced at GDC that its cloud gaming service would support higher framerates for VR titles, potentially making cloud-based VR gaming more viable.",
    link: "https://mixed-news.com",
    author: null,
    pubDate: new Date(Date.now() - 12 * 3600000).toISOString(),
    category: "software",
    tags: ["software"],
    imageUrl: null,
  },
  {
    id: "11",
    source: "arstechnica",
    sourceName: "Ars Technica",
    title: "Lynx XR Headset Maker Enters Liquidation Ahead of R2 Launch",
    snippet:
      "The company behind the Lynx mixed reality headset has entered liquidation proceedings, casting doubt on the future of its anticipated R2 headset.",
    link: "https://arstechnica.com",
    author: null,
    pubDate: new Date(Date.now() - 13 * 3600000).toISOString(),
    category: "hardware",
    tags: ["hardware"],
    imageUrl: null,
  },
  {
    id: "12",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "Meta Reverses Decision to Shut Down VR Version of Horizon Worlds",
    snippet:
      "After previously announcing it would shutter VR support for Horizon Worlds in favor of mobile, Meta appears to have reversed course following community backlash.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 14 * 3600000).toISOString(),
    category: "software",
    tags: ["meta", "software"],
    imageUrl: null,
  },
  {
    id: "13",
    source: "xrtoday",
    sourceName: "XR Today",
    title: "AR Smart Glasses Market Heats Up as Alibaba Unveils Display-Clad Pair",
    snippet:
      "Alibaba released a new pair of smart glasses with integrated displays, joining the growing field of companies pushing lightweight AR wearables into the consumer market.",
    link: "https://www.xrtoday.com",
    author: null,
    pubDate: new Date(Date.now() - 15 * 3600000).toISOString(),
    category: "hardware",
    tags: ["ar", "hardware"],
    imageUrl: null,
  },
  {
    id: "14",
    source: "venturebeat",
    sourceName: "VentureBeat",
    title: "AWE USA 2026 Returns to Long Beach This June — Largest XR Conference Yet",
    snippet:
      "The annual Augmented World Expo is set for June 15-18 in Long Beach, California, promising its biggest lineup of speakers and demos focused on spatial computing.",
    link: "https://venturebeat.com",
    author: null,
    pubDate: new Date(Date.now() - 16 * 3600000).toISOString(),
    category: "enterprise",
    tags: ["ar", "enterprise"],
    imageUrl: null,
  },
  {
    id: "15",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "Resident Evil Requiem Already Has a PC VR Mod One Week After Launch",
    snippet:
      "Modders have wasted no time bringing VR support to Capcom's latest Resident Evil entry, with a basic but functional mod already available for PC VR headsets.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 17 * 3600000).toISOString(),
    category: "gaming",
    tags: ["gaming"],
    imageUrl: null,
  },
  {
    id: "16",
    source: "uploadvr",
    sourceName: "UploadVR",
    title: "Firewall Ultra Shutting Down Online Servers After Just Three Years",
    snippet:
      "The tactical team shooter for PSVR 2 is officially going offline, ending its run as one of the few competitive multiplayer titles on Sony's VR platform.",
    link: "https://uploadvr.com",
    author: null,
    pubDate: new Date(Date.now() - 18 * 3600000).toISOString(),
    category: "gaming",
    tags: ["sony", "gaming"],
    imageUrl: null,
  },
  {
    id: "17",
    source: "techcrunch",
    sourceName: "TechCrunch",
    title: "Meta CTO Bosworth Reflects on Where VR Gaming Fell Short",
    snippet:
      "Meta's head of Reality Labs detailed his perspective on what the company could have done differently to better serve VR gaming audiences on the Quest platform.",
    link: "https://techcrunch.com",
    author: null,
    pubDate: new Date(Date.now() - 19 * 3600000).toISOString(),
    category: "enterprise",
    tags: ["meta", "enterprise"],
    imageUrl: null,
  },
  {
    id: "18",
    source: "roadtovr",
    sourceName: "Road to VR",
    title: "nDreams Announces Closure of Two Internal VR Studios",
    snippet:
      "One of VR's longest-running game developers confirmed it is shuttering two of its internal teams, restructuring operations amid shifting market conditions.",
    link: "https://www.roadtovr.com",
    author: null,
    pubDate: new Date(Date.now() - 20 * 3600000).toISOString(),
    category: "gaming",
    tags: ["gaming"],
    imageUrl: null,
  },
  {
    id: "19",
    source: "theverge",
    sourceName: "The Verge",
    title: "Microsoft Announces Project Helix — Next Xbox Console Codename Revealed",
    snippet:
      "While details are sparse, Microsoft's next console announcement has the VR community speculating about potential mixed reality integration.",
    link: "https://www.theverge.com",
    author: null,
    pubDate: new Date(Date.now() - 22 * 3600000).toISOString(),
    category: "hardware",
    tags: ["hardware"],
    imageUrl: null,
  },
  {
    id: "20",
    source: "mixed",
    sourceName: "Mixed News",
    title: "South Korean Company Shows Anti-Fatigue XR Solution at MWC Barcelona",
    snippet:
      "NP Inc demonstrated a unique wearable solution designed to combat employee fatigue during extended XR usage in enterprise settings.",
    link: "https://mixed-news.com",
    author: null,
    pubDate: new Date(Date.now() - 24 * 3600000).toISOString(),
    category: "enterprise",
    tags: ["enterprise", "ar"],
    imageUrl: null,
  },
];

export const MOCK_TRENDING = [
  { topic: "Steam Frame", count: 24, sources: 6 },
  { topic: "Apple Vision Pro 2", count: 19, sources: 5 },
  { topic: "Horizon Worlds", count: 15, sources: 4 },
  { topic: "PSVR 2 Jailbreak", count: 12, sources: 3 },
  { topic: "Quest Usage Record", count: 11, sources: 4 },
  { topic: "AWE 2026", count: 8, sources: 3 },
  { topic: "Little Nightmares VR", count: 7, sources: 2 },
  { topic: "Lynx Liquidation", count: 6, sources: 3 },
];
