import type { RSSSource } from "./types";

export const RSS_SOURCES: RSSSource[] = [
  // Tier 1: VR / AR / XR-native publications (no filter)
  {
    key: "roadtovr",
    name: "Road to VR",
    url: "https://www.roadtovr.com/feed/",
    priority: "primary",
  },
  {
    key: "uploadvr",
    name: "UploadVR",
    url: "https://uploadvr.com/feed/",
    priority: "primary",
  },
  {
    key: "auganix",
    name: "Auganix",
    url: "https://www.auganix.org/feed/",
    priority: "primary",
  },
  {
    key: "uctodayxr",
    name: "UC Today XR",
    url: "https://www.uctoday.com/tag/extended-reality/feed/",
    priority: "primary",
  },
  {
    key: "virtualrealitynews",
    name: "Virtual Reality News",
    url: "https://virtual.reality.news/rss",
    priority: "secondary",
  },
  {
    key: "skarredghost",
    name: "The Ghost Howls",
    url: "https://skarredghost.com/feed/",
    priority: "primary",
  },
  {
    key: "arinsider",
    name: "AR Insider",
    url: "https://arinsider.co/feed/",
    priority: "primary",
  },
  {
    key: "nextreality",
    name: "Next Reality",
    url: "https://next.reality.news/rss",
    priority: "primary",
  },

  // Tier 2: General tech / gaming feeds, filtered to VR/AR/XR content only
  {
    key: "engadget",
    name: "Engadget",
    url: "https://www.engadget.com/rss.xml",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "theverge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "arstechnica",
    name: "Ars Technica",
    url: "https://arstechnica.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "techradar",
    name: "TechRadar",
    url: "https://www.techradar.com/rss",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "tomshardware",
    name: "Tom's Hardware",
    url: "https://www.tomshardware.com/feeds/all",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "digitaltrends",
    name: "Digital Trends",
    url: "https://www.digitaltrends.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "gizmodo",
    name: "Gizmodo",
    url: "https://gizmodo.com/rss",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "mashable",
    name: "Mashable",
    url: "https://mashable.com/feeds/rss/all",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "slashgear",
    name: "SlashGear",
    url: "https://www.slashgear.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "thenextweb",
    name: "The Next Web",
    url: "https://thenextweb.com/feed",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "wccftech",
    name: "Wccftech",
    url: "https://wccftech.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "pcworld",
    name: "PCWorld",
    url: "https://www.pcworld.com/feed",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "windowscentral",
    name: "Windows Central",
    url: "https://www.windowscentral.com/feeds/all",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "pcgamer",
    name: "PC Gamer",
    url: "https://www.pcgamer.com/rss/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "rockpapershotgun",
    name: "Rock Paper Shotgun",
    url: "https://www.rockpapershotgun.com/feed",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "eurogamer",
    name: "Eurogamer",
    url: "https://www.eurogamer.net/?format=rss",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "gamespot",
    name: "GameSpot",
    url: "https://www.gamespot.com/feeds/news/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "kotaku",
    name: "Kotaku",
    url: "https://kotaku.com/rss",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "destructoid",
    name: "Destructoid",
    url: "https://www.destructoid.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "pushsquare",
    name: "Push Square",
    url: "https://www.pushsquare.com/feeds/news",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "gamedeveloper",
    name: "Game Developer",
    url: "https://www.gamedeveloper.com/rss.xml",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "eightylevel",
    name: "80 Level",
    url: "https://80.lv/feed",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "androidauthority",
    name: "Android Authority",
    url: "https://www.androidauthority.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "ninetofivegoogle",
    name: "9to5Google",
    url: "https://9to5google.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "ninetofivemac",
    name: "9to5Mac",
    url: "https://9to5mac.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "appleinsider",
    name: "AppleInsider",
    url: "https://appleinsider.com/rss/news",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "macrumors",
    name: "MacRumors",
    url: "https://www.macrumors.com/macrumors.xml",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "nvidiablog",
    name: "NVIDIA Blog",
    url: "https://blogs.nvidia.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "metanewsroom",
    name: "Meta Newsroom",
    url: "https://about.fb.com/news/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
  {
    key: "playstationblog",
    name: "PlayStation Blog",
    url: "https://blog.playstation.com/feed/",
    priority: "secondary",
    relevanceFilter: true,
  },
];
